redmine.issue.api.url=http://192.168.129.171:5017
redmine.api.url=${redmine.issue.api.url}/projects/fiscalizadores-autorizados
redmine.api.key=23a49b3d6ecc471fea061ebe8506cdfd343fe9ff

#redmine.issue.api.url=https://redmine4.sudolabs.com.py
#redmine.api.url=https://redmine4.sudolabs.com.py/projects/fizcalizadores-autorizados
#redmine.api.key=cddfb563f8beb40e82fd08f8e4616baaf41afd12
#server.servlet.context-path=/spring-boot-jsp
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
app.url=https://carnet.asuncion.gov.py
